In [172]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [198]:
input = {'Business name': ['Bakers Delight', 'BreadTop', 'Boost Juice', 'Cellini Cafe & Restaurant', 'Nike', 'Puma', 'Meyson Jewellery', 'Goldmark', 'Blue Nile', 'The Australia Ballet'], 'Type of business': [0, 0, 0, 0, 1, 1, 2, 2, 2, 2], 'Number of outlets': [46, 75, 20, 90, 80, 65, 50, 40, 25, 10] , 'Review Rating': [4.3, 4.2, 4.3, 4.5, 4.5, 4.6, 4.3, 4.7, 4.1, 4.2] }


df = pd.DataFrame(input)
print(df)



               Business name  Type of business  Number of outlets  \
0             Bakers Delight                 0                 46   
1                   BreadTop                 0                 75   
2                Boost Juice                 0                 20   
3  Cellini Cafe & Restaurant                 0                 90   
4                       Nike                 1                 80   
5                       Puma                 1                 65   
6           Meyson Jewellery                 2                 50   
7                   Goldmark                 2                 40   
8                  Blue Nile                 2                 25   
9       The Australia Ballet                 2                 10   

   Review Rating  
0            4.3  
1            4.2  
2            4.3  
3            4.5  
4            4.5  
5            4.6  
6            4.3  
7            4.7  
8            4.1  
9            4.2  


In [185]:
# scaler = MinMaxScaler()
# df['Number of outlets'] = scaler.fit_transform(df[['Number of outlets']])
# print(df)

In [186]:
shops = np.asarray(df[['Type of business', 'Number of outlets', 'Review Rating']].values.tolist())

print(shops)
print(len(shops))

[[ 0.  46.   4.3]
 [ 0.  75.   4.2]
 [ 0.  20.   4.3]
 [ 0.  90.   4.5]
 [ 1.  80.   4.5]
 [ 1.  65.   4.6]
 [ 2.  50.   4.3]
 [ 2.  40.   4.7]
 [ 2.  25.   4.1]
 [ 2.  10.   4.2]]
10


In [187]:
#1 = Yes, 0 = No
output = np.asarray([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [188]:
X = shops
Y = output

In [189]:
X.shape

(10, 3)

In [190]:
Y.shape

(10,)

In [191]:
clf = RandomForestClassifier()

In [192]:
clf.fit(X, Y)

RandomForestClassifier()

In [193]:
print(clf.feature_importances_)

[0.36167156 0.40340792 0.23492052]


In [194]:
print(clf.predict([[2, 30, 4.6]]))

[0]
